Repository AY2122S2-CS2103-F11-2/tp, pull requests merged in 2022-03, with the labels that each got.

#20 Update Help command in User Guide
  docs/UserGuide.md
Labels: type.Task

#19 Update personal information
  docs/AboutUs.md
  docs/images/tiewweijian.png
  docs/team/tiewweijian.md
Labels: type.Task

#23 Update delete command in User Guide
  docs/UserGuide.md
Labels: type.Task

#24 Update find (search) command in User Guide
  .gitignore
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/charmainehly.png
  docs/team/charmainehly.md
Labels: type.Task, Documentation

#31 Update site wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, Documentation

#32 Update list command in UG
  docs/UserGuide.md
Labels: type.Task

#29 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, Documentation

#35 Modify README.md and DeveloperGuide.md with simple use cases
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.Task, Documentation

#37 15 & 16 User Guide and About Us
  docs/AboutUs.md
  docs/images/domlimm.png
  docs/team/domlimm.md
  docs/team/johndoe.md
Labels: type.Task, Documentation

#46 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, Documentation

#47 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, Documentation

#49 Update Developer Guide for help command
  docs/DeveloperGuide.md
Labels: type.Enhancement, Documentation

#48 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, Documentation

#50 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, Documentation

#54 Add list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Task, Functionality

#53 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, Documentation

#51 Create help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#55 Add updated `add` command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/StudentID.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, type.Task, priority.High, Functionality

#60 Add delete command and empty list message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Story, priority.High, Functionality

#61 Enhance search command (Issue #56)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/leeenen.md
  docs/team/lzan98.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/CourseContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicate/CourseContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicateTest.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#59 Enhance `add` command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Email.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#64 Create HelpWindowUtil class
  src/main/java/seedu/address/commons/util/HelpWindowUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/commons/util/HelpWindowUtilTest.java
Labels: type.Enhancement, priority.High, Functionality

#81 Issue #79: Change `studentID` to `studentId` and its related classes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/predicate/CourseContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/StudentIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Low

#77 Issue #58: Update `add` command in UG/DG
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.Task, Documentation

#85 Issue #62 and #73: Update UG and DG for sort command and find command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High, Documentation

#87 Add ApplicationStatus and InterviewStatus
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/main/java/seedu/address/model/person/InterviewStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/ApplicationStatusTest.java
  src/test/java/seedu/address/model/person/InterviewStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, Functionality

#88 Update DG and UG with schedule command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, Documentation

#90 Add availabilities for each candidate
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Availability.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AvailabilityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High, Functionality

#76 Add sort command to sort across all candidate fields (Issue #72)
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.Low, Functionality

#93 Revert `delete` command in UG and DG to use `INDEX`
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, Documentation

#94 Update content of HelpWindow
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High, Functionality

#98 Issue #80: Enhancing `add` command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/candidate/ApplicationStatus.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/candidate/Course.java
  src/main/java/seedu/address/model/candidate/InterviewStatus.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/candidate/CandidateTest.java
  src/test/java/seedu/address/model/candidate/CourseTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, type.Bug, priority.High, Functionality

#104 Issue #103: Enable assertions in gradle
  build.gradle
Labels: type.Task, priority.High

#119 Change attributes of `InterviewStatus`
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/candidate/InterviewStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/candidate/InterviewStatusTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
Labels: type.Enhancement, priority.Medium, Functionality

#121 Integrate InterviewSchedule with clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug

#129 Issue #115: Update DeveloperGuide with `Find` command implementation
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/images/FindActivityDiagram.png
Labels: type.Task, priority.High, Documentation

#128 Create trigger for `ApplicationStatus`
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/candidate/ApplicationStatusTest.java
  src/test/java/seedu/address/model/candidate/InterviewStatusTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.Medium, Functionality

#131 Add `Edit` and `Help` commands in DG
  docs/DeveloperGuide.md
  docs/diagrams/plantuml/HelpWindowActivityDiagram.puml
  docs/diagrams/plantuml/StatusActivityDiagram.puml
  docs/images/HelpWindowActivityDiagram.png
  docs/images/StatusActivityDiagram.png
Labels: priority.High, Documentation

#133 Update DG with delete command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/images/DeleteActivityDiagram.png
Labels: Documentation

#136 Update MainApp.java for trial release
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High, Documentation

#135 Issue #126: Update schedule command to check for candidate availability
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#137 Issue #105: Introducing `Seniority` entity to `Candidate` model
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/candidate/ApplicationStatus.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/candidate/Course.java
  src/main/java/seedu/address/model/candidate/Email.java
  src/main/java/seedu/address/model/candidate/InterviewStatus.java
  src/main/java/seedu/address/model/candidate/Name.java
  src/main/java/seedu/address/model/candidate/Phone.java
  src/main/java/seedu/address/model/candidate/Seniority.java
  src/main/java/seedu/address/model/candidate/StudentId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/candidate/SeniorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCandidateTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
  src/test/java/seedu/address/testutil/CandidateUtil.java
  src/test/java/seedu/address/testutil/EditCandidateDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#143 Update availability field
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/candidate/Availability.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/candidate/AvailabilityTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#145 Change UI for Statuses
  src/main/java/seedu/address/ui/CandidateCard.java
  src/main/resources/view/CandidateListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, type.Task, priority.Medium, Functionality

#150 Issue #125: Create placeholders for GUI bottom panels
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/FocusListPanel.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/java/seedu/address/ui/InterviewListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CandidateListCard.fxml
  src/main/resources/view/FocusListCard.fxml
  src/main/resources/view/FocusListPanel.fxml
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High, Functionality

#166 Add `delete` to remove candidate's schedule
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/InterviewScheduleTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/interview/UniqueInterviewListTest.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#161 Issue #95: Update `add` command in User Guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium, Documentation

#167 Issue #124: Enhance `view` command to view interviews `today`, this `week` or this `month`
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/predicate/AllWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/ThisMonthWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/ThisWeekWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/TodayWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/WithinTimePeriodPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/InterviewScheduleTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/interview/predicate/AllWithinTimePeriodPredicateTest.java
  src/test/java/seedu/address/model/interview/predicate/ThisMonthWithinTimePeriodPredicateTest.java
  src/test/java/seedu/address/model/interview/predicate/ThisWeekWithinTimePeriodPredicateTest.java
  src/test/java/seedu/address/model/interview/predicate/TodayWithinTimePeriodPredicateTest.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#170 Improve availability UI
  src/main/java/seedu/address/model/candidate/Availability.java
  src/main/java/seedu/address/ui/CandidateCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/model/candidate/AvailabilityTest.java
Labels: type.Enhancement, priority.Low, Functionality

#163 Issue #89/#153: Update find/sort command for Seniority, Application Status and Interview Status
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedCandidate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicateTest.java
Labels: severity.High, type.Task, type.Bug, priority.High, Functionality

#173 Issue #157: Modify `schedule` command
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/AddScheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
Labels: priority.High, Functionality

#177 Issue #174: Refactor data filename to `talentassistant` instead of `addressbook`
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug, priority.High, Functionality

#175 Update automatic deletion of past scheduled interviews
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/InterviewScheduleTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.Task, priority.Medium, Functionality

#172 Issue #142: `seniority` input to allow only `int` values
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/candidate/Seniority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCandidate.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/ui/CandidateCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidCandidateAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidCandidateAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCandidateAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidCandidateAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCandidatesAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/candidate/SeniorityTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
  src/test/java/seedu/address/testutil/EditCandidateDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalCandidates.java
Labels: type.Task, type.Bug, priority.High, Functionality

#179 Issue #160 Implement `schedule delete` command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/predicate/SameInterviewPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteScheduleCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, priority.High, Functionality

#180 148-Focus-Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FocusCommandDiagram.puml
  docs/images/FocusCommandDiagram.png
  docs/images/blankprofile.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FocusCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FocusCommandParser.java
  src/main/java/seedu/address/ui/CandidateCard.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/FocusListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CandidateListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FocusCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FocusCommandParserTest.java
  src/test/java/seedu/address/ui/FocusCardTest.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#183 Issue #162: `find` based on Candidate's availability
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/candidate/predicate/AvailabilityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/candidate/predicate/AvailabilityContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#187 Issue #151: Update layout of GUI interview panel
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CourseContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/StudentIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/interview/predicate/AllWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/ThisMonthWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/ThisWeekWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/TodayWithinTimePeriodPredicate.java
  src/main/java/seedu/address/model/interview/predicate/WithinTimePeriodPredicate.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High, Functionality

#184 Allow InterviewStatus to be triggered by Scheduling
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/candidate/CandidateTest.java
  src/test/java/seedu/address/testutil/CandidateUtil.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#194 Issue #159: Implement `schedule edit` command
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/interview/UniqueInterviewListTest.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: type.Story, priority.High, Functionality

#198 Issue #178: Polishing the `UI`
  src/main/java/seedu/address/logic/commands/FocusCommand.java
  src/main/java/seedu/address/ui/CandidateCard.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/Styles.java
  src/main/resources/view/CandidateListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
Labels: severity.High, type.Task, type.Bug, priority.High, Functionality

#199 Issue #190: Fix split pane overflow scroll and headers
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low, type.Bug

#197 Fix implementation of find command for candidate field
  src/main/java/seedu/address/model/candidate/Seniority.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java
Labels: severity.Medium, type.Bug

#193 Issue #111: Add `edit` command related documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Story, type.Task, priority.High, Documentation

#200 Allow `InteviewStatus` to be triggered
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/typicalCandidatesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/candidate/CandidateTest.java
  src/test/java/seedu/address/testutil/TypicalCandidates.java
Labels: type.Enhancement, type.Task, priority.High, Functionality

#204 Issue #202: Adhoc Tasks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: severity.High, type.Task, type.Bug, priority.Medium, Documentation, Functionality

#208 #203-Remove `InterviewStatus` Trigger
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Task, type.Bug, priority.Medium

#209 Issue #207: Add `email` back into `add` command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/candidate/Email.java
  src/main/java/seedu/address/model/candidate/Seniority.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/candidate/EmailTest.java
  src/test/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/CourseContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/candidate/predicate/StudentIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
  src/test/java/seedu/address/testutil/CandidateUtil.java
Labels: severity.High, type.Bug, priority.High, Functionality

#219 Update `FocusCard` UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
Labels: type.Bug, priority.Low

#220 Update `HelpWindow` UI
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Medium

#223 Update profile picture in focus card
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
Labels: type.Task, priority.High, Functionality

#222 Update `schedule` commands in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
Labels: type.Task, Documentation

#226 Add schedule details in focus card
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
  src/test/java/seedu/address/ui/FocusCardTest.java
Labels: type.Task, priority.High, Functionality

#225 Update DG on IS and AS
  docs/DeveloperGuide.md
  docs/diagrams/plantuml/ApplicationStatusCommandDiagram.puml
  docs/diagrams/plantuml/EditCommandDiagram.puml
  docs/diagrams/plantuml/InterviewStatusDiagram.puml
  docs/images/ApplicationStatusCommandDiagram.png
  docs/images/EditCommandDiagram.png
  docs/images/InterviewStatusDiagram.png
Labels: priority.High, Documentation

#227 Change interviewList to interviewSchedule
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: type.Task, Functionality

#234 Refresh `Focus Panel`
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FocusCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/candidate/CandidateTest.java
Labels: type.Task, priority.High, Functionality

#238 Issue #237: Refactor `HelpWindow`
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, type.Bug, priority.Medium, Functionality

#230 Issue #164/165/168: Update UG/DG for sort, find and view
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High, Documentation

#247 Fix office hours logic
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: severity.High, type.Bug

#243 Remove random color generator for profile picture
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/java/seedu/address/ui/Styles.java
Labels: type.Bug, priority.Low, Functionality

#231 Issue #218: Add remark command (KIV)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/candidate/Remark.java
  src/main/java/seedu/address/model/candidate/predicate/AvailabilityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCandidate.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateCandidateAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCandidatesAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/candidate/RemarkTest.java
  src/test/java/seedu/address/model/candidate/predicate/RemarkContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCandidateTest.java
  src/test/java/seedu/address/testutil/CandidateBuilder.java
  src/test/java/seedu/address/testutil/TypicalCandidates.java
Labels: priority.Low, Functionality

#250 249-Fix `Delete` Bug
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High

#257 Issue #240: Address issues relating to `sort`, `find`, `remark` and UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/ui/CandidateCard.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/resources/view/CandidateListCard.fxml
  src/main/resources/view/FocusListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, Documentation

#256 Issues #254: Add loop to RemarkCommand to sync remark update to interview schedule
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: priority.High, Functionality

#258 Update logic of loading JSON files
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonSerializableInterviewSchedule.java
Labels: Functionality

#251 Issue #248 Implement `schedule clear` command
  src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/candidate/UniqueCandidateList.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
Labels: priority.High, Functionality

#255 #253-Refresh `FocusCard` when using `RemarkCommand`
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High, Functionality

#241 Issue #102: Edit command rework
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/candidate/Candidate.java
  src/main/java/seedu/address/model/candidate/UniqueCandidateList.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/candidate/UniqueCandidateListTest.java
Labels: severity.High, type.Enhancement, type.Task, type.Bug, priority.High, Functionality

#270 Change add command feedback
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: severity.Low, type.Bug

#269 Change feedback for `FocusCommand`
  src/main/java/seedu/address/logic/commands/FocusCommand.java
Labels: severity.Medium, type.Bug

#280 Update UG with schedule clear and warning for JSON
  docs/UserGuide.md
Labels: type.Task, Documentation

#278 Fix profile picture not showing
  src/main/java/seedu/address/ui/FocusCard.java
Labels: type.Bug, Functionality

#277 Fix feedback messages and update logic for scheduling
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: severity.Medium, Functionality

#265 Issues #263: Fix refresh on `view` when `remark` and `edit`
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: severity.Medium, type.Bug, Documentation

#286 Issue #260: Adhoc Tasks
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/ui/FocusCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FocusListCard.fxml
Labels: severity.High, type.Enhancement, type.Task, type.Bug, priority.High, Documentation, Functionality

#272 Feedback panel will reflect correct message
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, type.Bug, priority.High

#283 Issue #266: Standardise feedback messages for all commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FocusCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/candidate/predicate/ApplicationStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CandidateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/CourseContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/InterviewStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/SeniorityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/candidate/predicate/StudentIdContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: severity.Medium, type.Bug

#289 Focus clear panel
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High, Functionality

#288 Update help window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Medium, Functionality

#293 Issue #285: Bugfix: command textfield does not clear when focus panel is not loaded
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.High, type.Bug, priority.High, Functionality

#297 Update profile picture to show for `name` containing numbers
  src/main/java/seedu/address/ui/FocusCard.java
Labels: severity.High, type.Bug, priority.Medium, Functionality

#294 Change date format to dd-MM-YYYY
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
Labels: type.Task

#298 Change behaviour of edit command
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, type.Bug, priority.High

#299 Adhoc bugs
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
Labels: severity.High, type.Bug

#300 Fix new line in feedback box messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: severity.VeryLow, type.Bug

#303 Add UI picture for README
  docs/images/Ui.png
Labels: type.Task, priority.Low, Documentation

#302 Fix Tables UG
  docs/UserGuide.md
Labels: Documentation

#307 Schedule Bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
Labels: severity.High, type.Bug

#308 Change Version Number
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, Documentation
