Repository AY2122S2-CS2103-F11-2/tp, pull requests merged in 2022-04, with the labels that each got.

#351 Issue #324: Add restriction on `course` entity in UG
  docs/UserGuide.md
Labels: type.Bug, Documentation

#358 Edit `Focus` UG and `Start Up` Picture
  docs/UserGuide.md
  docs/images/focusui.png
  docs/images/startupui.png
Labels: priority.High, Documentation

#365 Add Strict ResolverStyle to DateTimeFormatter
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: severity.High, type.Bug

#367 Issue #344: Bug from `edit` after using `find` command
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, Functionality

#362 Issues #331, #338, #339, #345: Update UG for `add` and `edit`
  docs/UserGuide.md
Labels: type.Bug, priority.High, Documentation, Functionality

#369 Issue #158: Remove address entity from app
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/candidate/Address.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCandidateAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCandidatesAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/candidate/AddressTest.java
Labels: type.Bug, priority.High, Functionality

#357 Update UG for PED bugs and suggestions
  docs/UserGuide.md
Labels: priority.Medium, Documentation

#370 Issue #352: Update skeletal PPP with summary of contributions
  docs/team/charmainehly.md
Labels: Documentation

#368 Issue #364: Add acknowledgement for application's icon into DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, Documentation

#371 Update PPP
  docs/team/tiewweijian.md
Labels: priority.High, Documentation

#373 Update PPP
  docs/team/leeenen.md
Labels: type.Task, priority.High, Documentation

#366 Schedule Feedback Bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.High, type.Task, type.Bug, Functionality

#374 Change time to be 30 minutes instead of 31 minutes
  src/main/java/seedu/address/model/InterviewSchedule.java
Labels: severity.Low, type.Bug

#376 Update edit command format in UG
  docs/UserGuide.md
Labels: Functionality

#377 Create test cases for JsonAdaptedInterview
  src/main/java/seedu/address/model/candidate/Seniority.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/test/java/seedu/address/model/candidate/SeniorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInterviewTest.java
Labels: type.Task, priority.Medium, Functionality

#378 Remove tag attributes in the system
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Task, priority.Low, Functionality

#380 Issue #349: Fix bug in ellipsis for edit command message usage
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High, Functionality

#390 Issue #388/389: Update developer guide and PPP
  docs/DeveloperGuide.md
  docs/team/charmainehly.md
Labels: priority.High, Documentation

#384 Improve code quality and add test cases
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ScheduleCommand.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
  src/test/java/seedu/address/model/InterviewScheduleTest.java
  src/test/java/seedu/address/model/interview/UniqueInterviewListTest.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: severity.Low

#385 Issue #383: Update implementation on add feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddStep2.png
Labels: type.Task, priority.High, Documentation

#400 Issue #387: Update UI component in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High, Documentation

#402 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddScheduleSequenceDiagram.puml
  docs/diagrams/ScheduleLogicDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AddScheduleSequenceDiagram.png
  docs/images/ScheduleLogicDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
Labels: type.Task, Documentation

#414 Update Focus and Startup in Developers Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, Documentation

#403 Issues #386, #393: Update DG on `Model` component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High, Documentation

#421 Adhoc Issues: Update DG, UG and Readme
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/team/charmainehly.md
Labels: priority.High, Documentation

#423 Issue #418: Add `add` command manual testing
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, Documentation

#422 Issue #406: Update user stories / use cases
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
  docs/team/domlimm.md
Labels: type.Task, priority.High, Documentation

#427 Update JavaDocs
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/schedule/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/InterviewSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
Labels: type.Task, Documentation

#425 Issue #424: Bug Fix: Add line breaks for add candidate manual testing
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, Documentation

#430 Update edit details in UG
  docs/DeveloperGuide.md
Labels: Documentation

#426 Add author tags for relevant files
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyInterviewSchedule.java
  src/main/java/seedu/address/model/candidate/Remark.java
  src/main/java/seedu/address/model/candidate/UniqueCandidateList.java
  src/main/java/seedu/address/model/candidate/exceptions/CandidateNotFoundException.java
  src/main/java/seedu/address/model/candidate/exceptions/DuplicateCandidateException.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/CandidateListPanel.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/InterviewScheduleTest.java
  src/test/java/seedu/address/model/candidate/RemarkTest.java
  src/test/java/seedu/address/model/candidate/UniqueCandidateListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/CandidateUtil.java
  src/test/java/seedu/address/testutil/EditCandidateDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: Documentation

#416 Insert breaklines
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, Documentation

#433 Finalise PPP
  docs/team/lzan98.md
Labels: type.Task, Documentation

#435 Fix font size and formatting issues for PPP
  docs/team/lzan98.md
Labels: type.Task, Documentation

#438 Issue #411: Finalise PPP
  docs/team/domlimm.md
Labels: type.Task, priority.High, Documentation

#437 Finalise PPP
  docs/team/lzan98.md
Labels: type.Task, Documentation

#439 Finalize PPP
  docs/team/leeenen.md
Labels: Documentation

#431 Update DG with use cases and manual testing for `schedule` commands
  docs/DeveloperGuide.md
Labels: type.Task, Documentation

#412 Update saving data details in UG
  docs/DeveloperGuide.md
Labels: Documentation

#432 Update logic diagrams
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram_New.png
  docs/images/LogicClassDiagram.png
  docs/images/LogicClassDiagram_New.png
Labels: type.Task, priority.Low, Documentation

#440 Update sequence diagram for sort command
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/team/charmainehly.md
  src/main/java/seedu/address/model/candidate/predicate/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/interview/predicate/WithinTimePeriodPredicate.java
Labels: priority.High, Documentation

#442 Change javadocs for FocusCommandParser
  src/main/java/seedu/address/logic/parser/FocusCommandParser.java
Labels: type.Task, priority.High, Documentation

#443 Final change to PPP
  docs/team/lzan98.md
Labels: type.Task, Documentation

#441 Remove additional line in DG
  docs/DeveloperGuide.md
Labels: Documentation

#446 Fix minor formatting
  docs/DeveloperGuide.md
Labels: type.Task, Documentation

#444 Update PPP headings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/charmainehly.md
Labels: Documentation

#447 Fix remove link
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High, Documentation

#451 Issue #450: Fix bug in remark message
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: type.Bug, priority.High, Functionality
